version: "3"

dotenv:
  - ".env"

tasks:
  default:
    desc: "show all available tasks"
    cmds:
      - task --list-all
    silent: true

  tidy:
    desc: install pkg listed in go.mod
    cmds:
      - go mod tidy

  deps:
    desc: install dependencies
    cmds:
      - go install github.com/vektra/mockery/v3@v3.4.0
      - go install github.com/wadey/gocovmerge@latest
